// <auto-generated />
using System;
using Agencia_AT_DR4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agencia_AT_DR4.Migrations
{
    [DbContext(typeof(AgenciaContext))]
    [Migration("20260329184413_AddEntidades")]
    partial class AddEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Agencia_AT_DR4.Models.CidadeDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaisDestinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaisDestinoId");

                    b.ToTable("CidadesDestino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Rio de Janeiro",
                            PaisDestinoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Florianópolis",
                            PaisDestinoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Buenos Aires",
                            PaisDestinoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Lisboa",
                            PaisDestinoId = 3
                        });
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao@email.com",
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria@email.com",
                            Nome = "Maria Souza"
                        });
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.PacoteTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PacotesTuristicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeMaxima = 20,
                            DataInicio = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 2500.00m,
                            Titulo = "Carnaval no Rio"
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeMaxima = 15,
                            DataInicio = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 1800.00m,
                            Titulo = "Praias de Floripa"
                        },
                        new
                        {
                            Id = 3,
                            CapacidadeMaxima = 10,
                            DataInicio = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 3200.00m,
                            Titulo = "Buenos Aires Cultural"
                        });
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.PaisDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaisesDestino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "BR",
                            Nome = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "AR",
                            Nome = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PT",
                            Nome = "Portugal"
                        });
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacoteTuristicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteTuristicoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("CidadeDestinoPacoteTuristico", b =>
                {
                    b.Property<int>("DestinosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacotesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DestinosId", "PacotesId");

                    b.HasIndex("PacotesId");

                    b.ToTable("CidadeDestinoPacoteTuristico");
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.CidadeDestino", b =>
                {
                    b.HasOne("Agencia_AT_DR4.Models.PaisDestino", "PaisDestino")
                        .WithMany("Cidades")
                        .HasForeignKey("PaisDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaisDestino");
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.Reserva", b =>
                {
                    b.HasOne("Agencia_AT_DR4.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agencia_AT_DR4.Models.PacoteTuristico", "PacoteTuristico")
                        .WithMany("Reservas")
                        .HasForeignKey("PacoteTuristicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PacoteTuristico");
                });

            modelBuilder.Entity("CidadeDestinoPacoteTuristico", b =>
                {
                    b.HasOne("Agencia_AT_DR4.Models.CidadeDestino", null)
                        .WithMany()
                        .HasForeignKey("DestinosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agencia_AT_DR4.Models.PacoteTuristico", null)
                        .WithMany()
                        .HasForeignKey("PacotesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.PacoteTuristico", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Agencia_AT_DR4.Models.PaisDestino", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
